config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
	
  root 'home#index'
  get 'search', to: 'search#search'
 
  resources :authors
  
  resources :books do
    resources :comments
  end
  
  resources :categories
  
  resources :posts do
    resources :comments
  end

  resources :users do
    member do
      get :following, :followers
      get :feed
    end
  end
  
  resources :friends, only: [:create, :destroy] 
  resources :favorite_books, only: [:create, :destroy]

  resources :articles do
    resources :comments
  end
  get 'tags/:tag', to: 'articles#index', as: :tag, :constraints  => { :tag => /[^\/]+/ }
end

app/models/article.rb
class Article < ApplicationRecord
  has_and_belongs_to_many :books

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  has_many :comments, as: :commentable

  has_attached_file :photo_article
  validates_attachment_content_type :photo_article, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def self.tagged_with(name)
    Tag.find_by!(tag_name: name).articles
  end

  def self.tag_counts
    Tag.joins(:taggings).select('tags.id, tags.tag_name, count(taggings.tag_id) as count').
        group('taggings.tag_id, tags.id, tags.tag_name ')
  end

  def tag_list
    tags.map(&:tag_name).join(' ')
  end

  def tag_list=(names)
    self.tags = names.split(' ').map do |n|
      Tag.where(tag_name: n.strip).first_or_create!
    end
  end
end

app/models/author.rb
class Author < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  has_many :books
  has_and_belongs_to_many :categories

  has_attached_file :photo_author
  validates_attachment_content_type :photo_author, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  validates :fName, length: {in: 2..40}
  validates :lName, length: {in: 2..50}
  validates :biography, length: { in: 200..10000 }
  validates :birthplace, length: {in: 10..300}

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['fName^10', 'lName^10', 'text'],
            operator: 'AND'
          }
        }
      }
    )
  end
end

app/models/book.rb
require 'elasticsearch/model'

class Book < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  has_and_belongs_to_many :categories
  belongs_to :author

  has_attached_file :photo_book
  
  has_many :favorite_books, dependent: :destroy
  has_many :users, through: :favorite_books

  has_many :comments, as: :commentable

  validates_attachment_content_type :photo_book, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['title^10', 'text']
          }
        }
      }
    )
  end
end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :books
	has_and_belongs_to_many :authors

	validates :genre, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :commentable, polymorphic: true
end

app/models/favorite_book.rb
class FavoriteBook < ApplicationRecord	
	belongs_to :user
	belongs_to :book
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, as: :commentable
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings,  dependent: :destroy
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { email.downcase! }
  before_save   :downcase_email

  has_and_belongs_to_many :categories
  
  has_many :posts, dependent: :destroy

  has_many :likes
  has_many :liked_posts, :through => :likes, :source => :post

  has_many :comments

  has_many :active_friends, class_name: "Friend", 
                            foreign_key: "follower_id", 
                            dependent: :destroy
  has_many :following, through: :active_friends, source: :followed
  

  has_many :passive_friends, class_name:  "Friend",
                             foreign_key: "followed_id",
                             dependent: :destroy
  has_many :followers, through: :passive_friends, source: :follower

  
  has_many :favorite_books, dependent: :destroy
  has_many :books, through: :favorite_books

	validates :name, presence: true, length: { maximum: 40 }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
  validates :email, presence: true, length: { maximum: 100 }, format: {with: VALID_EMAIL_REGEX}, 
	          uniqueness: { case_sensitive: false }
  
  has_secure_password

  validates :password, presence: true, length: { minimum: 8 }

  has_attached_file :photo_user, 
    :default_url => "avatar2.jpg"

  validates_attachment_content_type :photo_user, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost    	
    BCrypt::Password.create(string, cost: cost)
  end

  def remember
    self.remember_token = SecureRandom.urlsafe_base64
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token) 
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def feed
    following_ids = "SELECT followed_id FROM friends WHERE follower_id = :user_id"
    Post.where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: id)
  end

  def favorite_book?(book)
    books.include?(book)
  end

  def favorite(book)
    books << book
  end

  def unfavorite(book)
    books.delete(book)
  end

  def liking_post?(post)
    liked_posts.include?(post)
  end

  def like(post)
    liked_posts << post
  end

  def dislike(post)
    liked_posts.delete(post)
  end
  
  private    
    def downcase_email
      self.email = email.downcase
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = if params[:tag]
      Article.tagged_with(params[:tag])
    else
      Article.all
    end
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update_attributes(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    Article.find(params[:id]).destroy
    redirect_to article_url
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title_article, :text_article, :photo_article, :tag_list,
                                      :category_ids => [], :book_ids => [])
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <br>
    <%= f.label :title_article %>
    <%= f.text_field :title_article, class: 'form-control' %>
    <br>

    <br>
    <%= f.label :text_article %>
    <%= f.text_area :text_article, class: 'form-control' %>

    <div class="field">
      <%= f.label :tag_list, "Tags (separated by commas)" %><br />
      <%= f.text_field :tag_list %>
    </div>

    <br>
    <%= f.label :photo_article %>
    <%= f.file_field :photo_article, class: 'form-control' %>
    <br>
    
    <%= f.label :book %><br>
    <%= f.collection_check_boxes :book_ids, Book.all, :id, :title do |check|%>
      <%= check.check_box %>
      <%= check.label %>
    <% end %>
    
    <%= f.submit "Create" %>
<% end %>

app/views/articles/edit.html.erb
<%= form_for(@article) do |f| %>
    <br>
    <%= f.label :title_article %>
    <%= f.text_field :title_article, class: 'form-control' %>
    <br>

    <br>
    <%= f.label :text_article %>
    <%= f.text_area :text_article, class: 'form-control' %>

    <br>
    <%= f.label :photo_article %>
    <%= f.file_field :photo_article, class: 'form-control' %>
    <br>
    
    <%= f.label :book %><br>
    <%= f.collection_check_boxes :book_ids, Book.all, :id, :title do |check|%>
      <%= check.check_box %>
      <%= check.label %>
    <% end %>
    
    <%= f.submit "Update" %>
<% end %>

app/views/articles/index.html.erb
<% if logged_admin? %>
<% else %>
  <h1>Articles</h1>

  <div id="tag_cloud">
    <% tag_cloud Article.tag_counts, %w[s m l] do |tag, css_class| %>
      <%= link_to tag.tag_name, tag_path(tag.tag_name), class: css_class %>
    <% end %>
  </div>

  <div id="articles">
    <% @articles.each do |article| %>
      <%= simple_format article.text_article %>
      <p>
        Tags: <%= raw article.tags.map(&:tag_name).map { |t| link_to t, tag_path(t) }.join(' ') %>
      </p>
      <p><%= link_to "Edit Article", edit_article_path(article) %></p>
    <% end %>
  </div>

  <p><%= link_to "New Article", new_article_path %></p>

<% end %>
<style>
  #tag_cloud {
  width: 400px;
  line-height: 1.6em;
  .s { font-size: 0.8em; }
  .m { font-size: 1.2em; }
  .l { font-size: 1.8em; }
}

</style>

app/views/articles/new.html.erb
<h2>NEW ARTICLE</h2>

<%= render 'form', article: @article %>