config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
	
  root 'home#index'
  get 'search', to: 'search#search'
 
  resources :authors
  
  resources :books do
    resources :comments
  end
  
  resources :categories
  
  resources :posts do
    resources :comments
  end

  resources :users do
    member do
      get :following, :followers
      get :feed
    end
  end
  
  resources :friends, only: [:create, :destroy] 
  resources :favorite_books, only: [:create, :destroy]

  resources :articles do
    resources :comments
  end
  get 'tags/:tag', to: 'articles#index', as: :tag, :constraints  => { :tag => /[^\/]+/ }
end

app/models/article.rb
class Article < ApplicationRecord
  has_and_belongs_to_many :books

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  has_many :comments, as: :commentable

  has_attached_file :photo_article
  validates_attachment_content_type :photo_article, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def self.tagged_with(name)
    Tag.find_by!(tag_name: name).articles
  end

  def self.tag_counts
    Tag.joins(:taggings).select('tags.id, tags.tag_name, count(taggings.tag_id) as count').
        group('taggings.tag_id, tags.id, tags.tag_name ')
  end

  def tag_list
    tags.map(&:tag_name).join(' ')
  end

  def tag_list=(names)
    self.tags = names.split(' ').map do |n|
      Tag.where(tag_name: n.strip).first_or_create!
    end
  end
end

app/models/author.rb
class Author < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  has_many :books
  has_and_belongs_to_many :categories

  has_attached_file :photo_author
  validates_attachment_content_type :photo_author, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  validates :fName, length: {in: 2..40}
  validates :lName, length: {in: 2..50}
  validates :biography, length: { in: 200..10000 }
  validates :birthplace, length: {in: 10..300}

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['fName^10', 'lName^10', 'text'],
            operator: 'AND'
          }
        }
      }
    )
  end
end

app/models/book.rb
require 'elasticsearch/model'

class Book < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  has_and_belongs_to_many :categories
  belongs_to :author

  has_attached_file :photo_book
  
  has_many :favorite_books, dependent: :destroy
  has_many :users, through: :favorite_books

  has_many :comments, as: :commentable

  validates_attachment_content_type :photo_book, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['title^10', 'text']
          }
        }
      }
    )
  end
end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :books
	has_and_belongs_to_many :authors

	validates :genre, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :commentable, polymorphic: true
end

app/models/favorite_book.rb
class FavoriteBook < ApplicationRecord	
	belongs_to :user
	belongs_to :book
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, as: :commentable
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings,  dependent: :destroy
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { email.downcase! }
  before_save   :downcase_email

  has_and_belongs_to_many :categories
  
  has_many :posts, dependent: :destroy

  has_many :likes
  has_many :liked_posts, :through => :likes, :source => :post

  has_many :comments

  has_many :active_friends, class_name: "Friend", 
                            foreign_key: "follower_id", 
                            dependent: :destroy
  has_many :following, through: :active_friends, source: :followed
  

  has_many :passive_friends, class_name:  "Friend",
                             foreign_key: "followed_id",
                             dependent: :destroy
  has_many :followers, through: :passive_friends, source: :follower

  
  has_many :favorite_books, dependent: :destroy
  has_many :books, through: :favorite_books

	validates :name, presence: true, length: { maximum: 40 }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
  validates :email, presence: true, length: { maximum: 100 }, format: {with: VALID_EMAIL_REGEX}, 
	          uniqueness: { case_sensitive: false }
  
  has_secure_password

  validates :password, presence: true, length: { minimum: 8 }

  has_attached_file :photo_user, 
    :default_url => "avatar2.jpg"

  validates_attachment_content_type :photo_user, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost    	
    BCrypt::Password.create(string, cost: cost)
  end

  def remember
    self.remember_token = SecureRandom.urlsafe_base64
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token) 
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def feed
    following_ids = "SELECT followed_id FROM friends WHERE follower_id = :user_id"
    Post.where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: id)
  end

  def favorite_book?(book)
    books.include?(book)
  end

  def favorite(book)
    books << book
  end

  def unfavorite(book)
    books.delete(book)
  end

  def liking_post?(post)
    liked_posts.include?(post)
  end

  def like(post)
    liked_posts << post
  end

  def dislike(post)
    liked_posts.delete(post)
  end
  
  private    
    def downcase_email
      self.email = email.downcase
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else 
      render 'new'
    end
  end
  
  def destroy
    Category.find(params[:id]).destroy
    redirect_to categories_url
  end

  def show
    @books = @category.books
  end

  private
    def category_params
      params.require(:category).permit(:genre)
    end

    def set_category
      @category = Category.find(params[:id])
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<% if logged_admin? %>
<% else %>
	<div class="container">
		<% @categories.each do |c| %>
			<table border="1" width="100%" style="padding: 10px;">
				<tr>
					<td colspan="5"><br><br><h1 class="categories"><%= c.genre%></h1><hr></td>
				</tr>
				<tr>
					<td><h1>IMAGE</h1></td>
					<td><h1>IMAGE</h1></td>
					<td><h1>IMAGE</h1></td>
					<td><h1>IMAGE</h1></td>
					<td><h1>IMAGE</h1></td>
				</tr>
			</table>
		<% end %>
	<br>
	</div>
<% end %>

app/views/categories/show.html.erb
<div align="center"><h3 class="category-book">Books &gt; <%= @category.genre %></h3></div>
<div align="center"><h1 class="category"><%= @category.genre %></h1></div>
<% @books.each_slice(5) do |book|%>
	<table class="category-book" align="center">
		<% if book.length == 5 %>
			<tr class="tr-category-book">
				<td colspan="2" class="td-category-book">
					<div id="category-book-item" style="background: #22264b">
				  	<div class="category-book-image">
				  		<%= image_tag book[0].photo_book.url, :size => "240x360", id: "ibook"%>
				  	</div>
				  </div>
				  <div id="category-book-link">
				  	<%= link_to book[0].title, book_path(book[0]), class: 'c-book-link-text'%>
				  	<%= link_to "by  " + book[0].author.fName + "  " + book[0].author.lName, 
				  		  author_path(book[0].author), class: 'c-book-link-author'%>
				  </div>
				</td>
				<td colspan="2" class="td-category-book">
				  <div id="category-book-item" style="background: #b56969">
				  	<div class="category-book-image">
				  		<%= image_tag book[1].photo_book.url, :size => "240x360", id: "ibook"%>
				  	</div>
				  </div>
				  <div id="category-book-link">
				  	<%= link_to book[1].title, book_path(book[1]), class: 'c-book-link-text'%>
				  	<%= link_to "by  " + book[1].author.fName + "  " + book[1].author.lName, 
				  		  author_path(book[1].author), class: 'c-book-link-author'%>
				  </div>
				</td>
				<td colspan="2" class="td-category-book">
				  <div id="category-book-item" style="background: #e6cf8b">
				  	<div class="category-book-image">
				  		<%= image_tag book[2].photo_book.url, :size => "240x360", id: "ibook"%>
				  	</div>
				  </div>
				  <div id="category-book-link">
				  	<%= link_to book[2].title, book_path(book[2]), class: 'c-book-link-text'%>
				  	<%= link_to "by  " + book[2].author.fName + "  " + book[2].author.lName, 
				  		  author_path(book[2].author), class: 'c-book-link-author'%>
				  </div>
				</td>
		  </tr>
		  <tr class="tr-category-book">
				<td colspan="3" class="td-category-book">
				  <div id="category-book-item-two" style="background: #e6cf8b">
				  	<div class="category-book-image-two">
				  		<%= image_tag book[3].photo_book.url, :size => "315x480", id: "ibook-two"%>
				  	</div>
				  </div>
				  <div id="category-book-link">
				  	<%= link_to book[3].title, book_path(book[3]), class: 'c-book-link-text'%>
				  	<%= link_to "by  " + book[3].author.fName + "  " + book[3].author.lName, 
				  		  author_path(book[3].author), class: 'c-book-link-author'%>
				  </div>
				</td>
				<td colspan="3" class="td-category-book-two">
				  <div id="category-book-item-two" style="background: #22264b">
				  	<div class="category-book-image-two">
				  		<%= image_tag book[4].photo_book.url, :size => "315x480", id: "ibook-two"%>
				  	</div>
				  </div>
				  <div id="category-book-link">
				  	<%= link_to book[4].title, book_path(book[4]), class: 'c-book-link-text'%>
				  	<%= link_to "by  " + book[4].author.fName + "  " + book[4].author.lName, 
				  		  author_path(book[4].author), class: 'c-book-link-author'%>
				  </div>
				</td>
		  </tr>
		<% end %>
	</table>
<% end %>